import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { dir } from "i18next";
import ClientProviders from "../ClientProviders";
import MainLayout from "../../libs/vocab/layout/MainLayout";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return ["en", "vi"].map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }: { children: React.ReactNode; params: Promise<{ locale: string }> }) {
    const { locale } = await params;

    return (
        <html lang={locale} dir={dir(locale)}>
            <body className={inter.className}>
                <ClientProviders>
                    <MainLayout>{children}</MainLayout>
                </ClientProviders>
            </body>
        </html>
    );
}
