export const lessonPlanKeys = {
  add_popup: {
    title: "add_popup.title",
    info: "add_popup.info",
    name: "add_popup.name",
    name_placeholder: "add_popup.name_placeholder",
    level: "add_popup.level",
    tab_task: "add_popup.tab_task",
    tab_game: "add_popup.tab_game",
    content_label: "add_popup.content_label",
    task_hint: "add_popup.task_hint",
    task_line: "add_popup.task_line",
    crossword_placeholder: "add_popup.crossword_placeholder",
    save: "add_popup.save",
  },
  detail: {
    title: "detail.title",
    no_words: "detail.no_words",
    open_audio: "detail.open_audio",
    task: "detail.task",
    game: "detail.game",
    game_prefix: "detail.game_prefix",
  },
  col_id: "col_id",
  col_name: "col_name",
  col_teacher: "col_teacher",
  col_level: "col_level",
  col_warm_up: "col_warm_up",
  col_vocab: "col_vocab",
  col_grammar: "col_grammar",
  col_listening: "col_listening",
  col_writing: "col_writing",
  col_speaking: "col_speaking",
  col_actions: "col_actions",
  action_view: "action_view",
  action_edit: "action_edit",
  action_download: "action_download",
  delete_title: "delete_title",
} as const;

export type LessonPlanKey = typeof lessonPlanKeys[keyof typeof lessonPlanKeys];
